### ISSUE TITLE
Fails building on master

### ISSUE THREAD

**Issue by ruwix** [first-rust-competition/ds-rs#2]
Trimmed due to being excessively long

```error[E0277]: `*mut (dyn std::ops::Fn() + 'static)` cannot be shared between threads safely
   --> src/ds/conn.rs:111:25
    |
111 |                         tokio::spawn(tcp_conn(state.clone(), target_ip.clone(), rx));
    |                         ^^^^^^^^^^^^ `*mut (dyn std::ops::Fn() + 'static)` cannot be shared between threads safely
    |
   ::: /home/ruwix/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.1/src/task/spawn.rs:49:17
    |
49  |     T: Future + Send + 'static,
    |                 ---- required by this bound in `tokio::task::spawn::spawn`
    |
    = help: within `bitflags::core::fmt::Void`, the trait `std::marker::Sync` is not implemented for `*mut (dyn std::ops::Fn() + 'static)`
    = note: required because it appears within the type `std::marker::PhantomData<*mut (dyn std::ops::Fn() + 'static)>`
    = note: required because it appears within the type `bitflags::core::fmt::Void`
    = note: required because of the requirements on the impl of `std::marker::Send` for `&bitflags::core::fmt::Void`
    = note: required because it appears within the type `std::fmt::ArgumentV1<'_>`
    = note: required because it appears within the type `[std::fmt::ArgumentV1<'_>; 1]`
    = note: required because it appears within the type `for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14, 't15, 't16, 't17, 't18, 't19, 't20, 't21, 't22, 't23, 't24, 't25, 't26, 't27, 't28, 't29, 't30, 't31, 't32, 't33, 't34, 't35, 't36, 't37, 't38, 't39, 't40, 't41, 't42, 't43> {std::sync::Arc<ds::state::DsState>, std::string::String, futures_channel::mpsc::UnboundedReceiver<ds::Signal>, fn(std::result::Result<tokio::net::tcp::stream::TcpStream, std::io::Error>) -> std::result::Result<<std::result::Result<tokio::net::tcp::stream::TcpStream, std::io::Error> as std::ops::Try>::Ok, <std::result::Result<tokio::net::tcp::stream::TcpStream, std::io::Error> as std::ops::Try>::Error> {<std::result::Result<tokio::net::tcp::stream::TcpStream, std::io::Error> as std::ops::Try>::into_result}, fn(&'r std::string::String) -> impl bitflags::core::future::future::Future {tokio::net::tcp::stream::TcpStream::connect::<&'r std::string::String>}, for<'t44> fn(std::fmt::Arguments<'t44>) -> std::string::String {std::fmt::format}, fn(&'s [&'s str], &'s [std::fmt::ArgumentV1<'s>]) -> std::fmt::Arguments<'s> {std::fmt::Arguments::<'s>::new_v1}, &'t0 str, &'t1 str, [&'t2 str; 2], &'t3 [&'t4 str], &'t5 [&'t6 str; 2], std::string::String, &'t7 std::string::String, (&'t8 std::string::String,), [std::fmt::ArgumentV1<'t9>; 1], &'t10 [std::fmt::ArgumentV1<'t11>], &'t12 [std::fmt::ArgumentV1<'t13>; 1], std::fmt::Arguments<'t14>, std::string::String, &'t15 std::string::String, impl bitflags::co```

**Comment by Redrield** [comment]
This failure condition is known and was mentioned in #1 when I was performing the rewrite. For the moment, the solution is to use a nightly compiler. I'll update the README to reflect this
